// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJYizlIxthFQY5GdFMDHXGV96wSWIBlr4',
    appId: '1:35978926454:android:942bd92f9ad825a0344257',
    messagingSenderId: '35978926454',
    projectId: 'groceryapp-86926',
    storageBucket: 'groceryapp-86926.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEvjXauZssbQnGoU7Qrpx2ihdl2KQJxOY',
    appId: '1:35978926454:ios:73dfcbba13f599f5344257',
    messagingSenderId: '35978926454',
    projectId: 'groceryapp-86926',
    storageBucket: 'groceryapp-86926.appspot.com',
    androidClientId: '35978926454-6bngeqe9dhdulv3rc0853m0grpn3ln5i.apps.googleusercontent.com',
    iosClientId: '35978926454-bs5j9jft2om9ipoaru1u3l594cd81qh2.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDeliveryMeal',
  );
}
